# Numpy for Data Science

In [1]:
import numpy as np

## Array Attribute

### 1-D Array :

In [2]:
a = np.array([1,2,3,4,5])
a

array([1, 2, 3, 4, 5])

In [3]:
type(a) # numpy.ndarray --> n dimantion array

numpy.ndarray

In [4]:
a.ndim

1

In [5]:
a.shape       # 5 column , no rows

(5,)

### 2-D Array :

In [7]:
b = np.array([[1,2,3],
              [4,5,6]])
b

array([[1, 2, 3],
       [4, 5, 6]])

In [9]:
b.shape           # 2 rows , 3 column

(2, 3)

In [11]:
b.dtype           # dtype --> data type

dtype('int64')

In [13]:
b.size            # Total element

6

### 3-D Array :

In [29]:
c = np.array([[[1,2,3],
              [4,5,6],
              [7,8,9]],
              
            [[11,12,13],    # imagine that 1-9 in up of 10-18
             [14,15,16],
             [17,19,19]]])
c

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[11, 12, 13],
        [14, 15, 16],
        [17, 19, 19]]])

### Memory check :

In [31]:
a.nbytes , b.nbytes , c.nbytes

(40, 48, 144)

### Zeros & Ones :

In [37]:
zeros_arr = np.zeros((3,3) , dtype=int)
zeros_arr

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [39]:
ones_arr = np.ones((4,4) , dtype=int)
ones_arr

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

### Different values :

In [41]:
arr_3 = np.full((4,4) , 12)
arr_3

array([[12, 12, 12, 12],
       [12, 12, 12, 12],
       [12, 12, 12, 12],
       [12, 12, 12, 12]])

### Identity matrix ( I ) :

In [43]:
i_3 = np.identity(3, dtype=int)
i_3

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

### Eye :

In [45]:
eye = np.eye(3 , dtype=int)
eye

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [48]:
eye = np.eye(4, dtype= int , k = 1)
eye           # k = 1 --> mail row will up by 1

array([[0, 1, 0, 0],
       [0, 0, 1, 0],
       [0, 0, 0, 1],
       [0, 0, 0, 0]])

### Arrange :

In [52]:
arrange = np.arange(0,100,10)       # like a python range() function
arrange

array([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

### Linspace :

In [54]:
linspace = np.linspace(1,100,20)      # (start , end , how many values)
linspace

array([  1.        ,   6.21052632,  11.42105263,  16.63157895,
        21.84210526,  27.05263158,  32.26315789,  37.47368421,
        42.68421053,  47.89473684,  53.10526316,  58.31578947,
        63.52631579,  68.73684211,  73.94736842,  79.15789474,
        84.36842105,  89.57894737,  94.78947368, 100.        ])

In [55]:
linspace = np.linspace(1,100,20 , dtype=int)      # (start , end , how many values)
linspace

array([  1,   6,  11,  16,  21,  27,  32,  37,  42,  47,  53,  58,  63,
        68,  73,  79,  84,  89,  94, 100])

### Empty :

In [57]:
empty = np.empty((1,5))
empty

array([[4.68727465e-310, 0.00000000e+000, 4.68825224e-310,
        4.68825192e-310, 2.37151510e-322]])

## Array Indexing :

### Index :

In [59]:
a = np.array([1,2,3,4,5,6,7])
a[0]            # as like normal indexing

1

### Random array :

In [65]:
random = np.random.randint(1,100 , size = (5,5))
random        # 1-100 random number 5x5 matrix

array([[45, 10, 75, 63, 86],
       [ 8, 39, 76, 12, 50],
       [54, 24, 54, 30, 49],
       [97, 39, 97, 77, 32],
       [10, 57, 58, 29, 92]])

### Index access 2-D array :

In [71]:
x = random[0][0]           # row 0 , culumn 0
x

45

In [72]:
y = random[0,0]           # rew 0 , culumn 0         
y

45

### Index access 3-D array :

In [77]:
random = np.random.randint(1,100 , size=(2,3,4))
random          # size(2,3,4) --> 3 : row  , 4 : column and 2 stage

array([[[69, 56, 92, 65],
        [66, 45,  5, 42],
        [89, 41, 26, 90]],

       [[58, 53, 48, 43],
        [13, 16, 50, 43],
        [97, 64, 82, 44]]])

In [78]:
x = random[0][0][0]
x

69

In [80]:
x = random[0,0,0]
x

69

## Array Slicing :

### Slicing 1-D array :

In [81]:
a = np.array([1,2,3,4,5,6,7,8,9])
a[1:4]

array([2, 3, 4])

In [82]:
a[:6]

array([1, 2, 3, 4, 5, 6])

In [84]:
a[2:]

array([3, 4, 5, 6, 7, 8, 9])

### Slicing 2-D array :

In [87]:
b = np.array([[1,2,3],
             [4,5,6],
             [7,8,9]])
b[0:2 , 0:1]   # row , column

array([[1],
       [4]])

## Manipulate array shape :

In [88]:
# Total 5 way:
    # 1. reshape() 
    # 2. resize()
    # 3. revel()
    # 4. flatten()
    # 5. defining array shape

### 1. reshape() :

In [91]:
b = np.array([[1, 2, 3] , 
              [4, 5, 6]])
np.reshape(b,(3,2))     # if element is not emough it will show element error

array([[1, 2],
       [3, 4],
       [5, 6]])

### 2. resize() :

In [94]:
# to solve this element error we can use resize()
b = np.array([[1, 2, 3] , 
              [4, 5, 6]])
np.resize(b, (4,3))   # repeat the element if extra need

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

### 3. revel () :

In [97]:
# change main array 
b = np.array([[1, 2, 3] , 
              [4, 5, 6]])
ravel = np.ravel(b)
ravel

array([1, 2, 3, 4, 5, 6])

In [99]:
ravel[0] = 100              # return a view of array and change main array 
ravel

array([100,   2,   3,   4,   5,   6])

### 4. flatten() :

In [111]:
# convart any array to 1-D array
# don't change main array
b = np.array([[1, 2, 3] , 
             [4, 5, 6]])
flatten = b.flatten()       # return a copy of arry and can't change main array
flatten

array([1, 2, 3, 4, 5, 6])

In [113]:
flatten[0] = 100            # change flatten only not b
b

array([[1, 2, 3],
       [4, 5, 6]])

### 5. defining array shape :

In [117]:
b = np.array([[1, 2, 3] , 
             [4, 5, 6]])
b.shape = (3, 2)            # need equal element
b

array([[1, 2],
       [3, 4],
       [5, 6]])

## Array staking :

### hstake() :

In [119]:
a = np.arange(1,10).reshape(3,3)    # create a 2-D array 1 to 9
b = 2*a                             # 2 * all element
b

array([[ 2,  4,  6],
       [ 8, 10, 12],
       [14, 16, 18]])

In [120]:
x = np.hstack((a,b))                # a + b in horizontal
x

array([[ 1,  2,  3,  2,  4,  6],
       [ 4,  5,  6,  8, 10, 12],
       [ 7,  8,  9, 14, 16, 18]])

### vstake() :

In [121]:
y = np.vstack((a,b))                # a + b in vartical 
y

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [ 2,  4,  6],
       [ 8, 10, 12],
       [14, 16, 18]])

### column stake :

In [122]:
z = np.column_stack((a , b))        # semilar to hstack
z

array([[ 1,  2,  3,  2,  4,  6],
       [ 4,  5,  6,  8, 10, 12],
       [ 7,  8,  9, 14, 16, 18]])

In [123]:
z = np.row_stack((a , b))           # semilar to vstack
z

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [ 2,  4,  6],
       [ 8, 10, 12],
       [14, 16, 18]])

### concatinate :

In [124]:
z = np.concatenate((a,b) , axis=1)  # axis 1 = horaizonal and azis 0 = vartical
z

array([[ 1,  2,  3,  2,  4,  6],
       [ 4,  5,  6,  8, 10, 12],
       [ 7,  8,  9, 14, 16, 18]])